// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Tape = require("bs-tape/lib/js/src/Tape.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Redis = require("redis");
var BsCallback = require("bs-callback/lib/js/src/bsCallback.js");

Tape.test("get/set", (function (t) {
        Curry._1(t[/* plan */0], 1);
        var client = new Redis.createClient();
        return BsCallback.finish(/* None */0, BsCallback.$great$great((function (param) {
                          client.set("ping", "pong", param);
                          return /* () */0;
                        }), (function () {
                          return BsCallback.$great$great((function (param) {
                                        client.get("ping", param);
                                        return /* () */0;
                                      }), (function (res) {
                                        return BsCallback.$great$great((function (param) {
                                                      client.quit(param);
                                                      return /* () */0;
                                                    }), (function () {
                                                      Curry._3(t[/* equalStr */10], /* None */0, res, "pong");
                                                      return (function (param) {
                                                          return BsCallback.$$return(/* () */0, param);
                                                        });
                                                    }));
                                      }));
                        })));
      }));

/*  Not a pure module */
