// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Redis = require("redis");
var BsAsyncMonad = require("bs-async-monad/lib/js/src/bsAsyncMonad.js");

var c = new Redis.createClient();

BsAsyncMonad.Callback[/* finish */26](/* None */0, BsAsyncMonad.Callback[/* >> */5]((function (param) {
            c.set("bingo2", "bingo", param);
            return /* () */0;
          }), (function () {
            return BsAsyncMonad.Callback[/* >> */5]((function (param) {
                          c.quit(param);
                          return /* () */0;
                        }), (function () {
                          var partial_arg = BsAsyncMonad.Callback[/* return */2];
                          return (function (param) {
                              return partial_arg(/* () */0, param);
                            });
                        }));
          })));

exports.c = c;
/* c Not a pure module */
