// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Redis = require("redis");
var BsCallback = require("bs-callback/lib/js/src/bsCallback.js");

var c = new Redis.createClient();

BsCallback.finish(/* None */0, BsCallback.$great$great((function (param) {
            c.set("bingo2", "bingo", param);
            return /* () */0;
          }), (function () {
            return BsCallback.$great$great((function (param) {
                          c.quit(param);
                          return /* () */0;
                        }), (function () {
                          return (function (param) {
                              return BsCallback.$$return(/* () */0, param);
                            });
                        }));
          })));

exports.c = c;
/* c Not a pure module */
